name: jevents test

on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master, test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        cd jevents ; make
    - name: tester
      run: |
        cd jevents
        ./listevents
        ./examples/jestat true
        ./tester
  
